### PR TITLE
Add support for PHP 5.5+, as we can't send file using @ anymore

### PR DESCRIPTION
**Pull request by benji07**

### CODE REVIEW

**Comment by hyvs** [comment]
woah ! essential fix. Thanks you @benji07 

:+1: :+1:

**Comment by vrcAlbert** [comment]
:+1: !

**Comment by Clayment** [comment]
:+1:

**Comment by charlthibault** [comment]
Thank you @benji07 for this fix

**Comment by pierrecol** [comment]
Merci Charles,

On peut savoir d’où proviennent ces aouts de code : quel client ? quel intégrateur ?

—
Pierre

**Pull request merged**
